apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "mutating-webhook-configuration"
webhooks:
  - name: "mutating-webhook-configuration"
    namespaceSelector:
      matchExpressions:
        - key: nuwa-injection
          operator: In
          values: ["enabled"]
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: NoneOnDryRun
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01ETXlPREEzTURneE9Wb1hEVE13TURNeU5qQTNNRGd4T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTVFrCkFSOHZKV1NHN0pOTm56bzBWSXkrUnhEL2hlaDFTZDJhOU5nQ1d4eUttMCtDNlAzZzJaN0xrQmw0bklqcDl1dHYKSzZ5SjJBL1ZHOWtST2F3d0IweGNMN0Zoa2pMRWdNb21FM1h2Z1NZSzhTc0NWUmdGWjJ5SjBaMkE4TlZOZkdWbApUZ2w5SEVacEtWQ1lqcTdDUlZlcER1MjJMZmZXd21qZmhrRThHK3RNQWtJdkxBcDhZSGc2bnpYb1VqSzNBeDFGClhiSG0veUpJblNGY3ZjSnBjdURYanhzTDdpMzhBdXZzajZmSjZHMnN0bFNyalhvUk95dFRqWmw1S1RTQ3lWMVIKRW1taUlmN2FvbVZ6TkVvajh1b2wrUlRkcFdhUEYwSHlrSnVZWWtCYVZEOGQ3SExuMytpMWdrL1FBU3Q4NVJvRwo2N3VUb3RwaDJWYnkwdE1PenpFQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCOFFZZ0d1cDgwNVVCeGpEVFZGQkZKbisxdC8KNG5JZ2FLQzVneGhzbDNHL1VDZDJaZGExZ1p6aHVFbGNGZVc0TjN3aU1QU1gxK2xaeTc5UmgvbmhuZy85OTFsbApWTndtNkU1WEF6WS9JYnNpWm5LTXE4WjlpQk9CM25nb0x4bXRyQ1NRQ2VaR2JReGtaZVF1Q2wzbjVZTFBFRERrCjhvd2R1dVp5N0JvUkg4OG02Tm52YURLZWxFVVZ5VDhHRVlwZDlQK3YvdmpPU2R2SlFORmtKeFYrcW1wQTQ3OGMKdG9kNFFkQkFxWWtxaVMvM0NKODVtOExzb3g4SXJudDJVT0xaZ2tXMnZSR2U5OVpVdDRsZytaSzNaL0xvQi9PLwpWSENubldvenBPdXJWZy9aL2lGb2JvVUlaSkNhQU54STBFUE52c3NWcTFReUJoK0RNYlVweTQ0WElGaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name:  nuwa-controller-manager-service
        namespace: nuwa-system
        path: /mutating-pods
    failurePolicy: Ignore  #  Fail/Ignore
    name: injector.nuwa.io
